// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsKygs6WElUNzu-ju9jOkgr_ki9Ng766I',
    appId: '1:82435809574:web:d49b6b1378ee7484f621e7',
    messagingSenderId: '82435809574',
    projectId: 'unesa-sporthub',
    authDomain: 'unesa-sporthub.firebaseapp.com',
    storageBucket: 'unesa-sporthub.firebasestorage.app',
    measurementId: 'G-H15G9305VC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQxY-5Lmbqjg_t-FiKzznTe6L5aZooJNY',
    appId: '1:82435809574:android:49f9825c128d28f2f621e7',
    messagingSenderId: '82435809574',
    projectId: 'unesa-sporthub',
    storageBucket: 'unesa-sporthub.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-3EDuB1wIaNREljfgsciT7QVWh3XssH4',
    appId: '1:82435809574:ios:e03b7c18b5d67a9af621e7',
    messagingSenderId: '82435809574',
    projectId: 'unesa-sporthub',
    storageBucket: 'unesa-sporthub.firebasestorage.app',
    iosBundleId: 'com.example.bookingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-3EDuB1wIaNREljfgsciT7QVWh3XssH4',
    appId: '1:82435809574:ios:e03b7c18b5d67a9af621e7',
    messagingSenderId: '82435809574',
    projectId: 'unesa-sporthub',
    storageBucket: 'unesa-sporthub.firebasestorage.app',
    iosBundleId: 'com.example.bookingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDsKygs6WElUNzu-ju9jOkgr_ki9Ng766I',
    appId: '1:82435809574:web:a472f604ed3dca41f621e7',
    messagingSenderId: '82435809574',
    projectId: 'unesa-sporthub',
    authDomain: 'unesa-sporthub.firebaseapp.com',
    storageBucket: 'unesa-sporthub.firebasestorage.app',
    measurementId: 'G-FR8PSKFYHE',
  );
}
